# Generated by Django 2.2 on 2019-04-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.CharField(max_length=200, null=True)),
                ('score', models.IntegerField(null=True)),
                ('bid', models.IntegerField(null=True)),
                ('tricks', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('cardOnTable', models.CharField(max_length=20, null=True)),
                ('turnOrder', models.IntegerField(null=True)),
                ('spotOnTable', models.IntegerField(null=True)),
            ],
        ),
    ]
