# Generated by Django 2.2 on 2019-04-27 01:34

from django.db import migrations


def player_maker(apps, schema_editor):
    Player = apps.get_model("players", "Player")
    player1 = Player(hand='', score=0, bid=0, tricks=0, name="Player One", cardOnTable="", turnOrder=0, spotOnTable=0)
    player1.save()
    player2 = Player(hand='', score=0, bid=0, tricks=0, name="Player Two", cardOnTable="", turnOrder=1, spotOnTable=1)
    player2.save()
    player3 = Player(hand='', score=0, bid=0, tricks=0, name="Player Three", cardOnTable="", turnOrder=2, spotOnTable=2)
    player3.save()
    player4 = Player(hand='', score=0, bid=0, tricks=0, name="Player Four", cardOnTable="", turnOrder=3, spotOnTable=3)
    player4.save()


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(player_maker)
    ]