# Generated by Django 2.2 on 2019-04-27 00:50

from django.db import migrations, models
from rspades import build


def deck_maker(apps, schema_editor):
    Deck = apps.get_model("decks", "Deck")
    suits = ['Spades', 'Hearts', 'Diamonds', 'Clubs']  # seed for deck of cards
    ranks = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
    deck1 = Deck(cards=build(suits, ranks))
    deck1.save()


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(deck_maker)
    ]
