# Generated by Django 2.2 on 2019-05-13 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '__first__'),
        ('players', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trump', models.IntegerField(null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck', to='decks.Deck')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='players.Player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='players.Player')),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player3', to='players.Player')),
                ('player4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player4', to='players.Player')),
            ],
        ),
    ]
