# Generated by Django 2.2 on 2019-04-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.CharField(default='\n<h1>The Pack\n    <p>The standard 52-card pack is used.</p>\n</h1>\n\n<h2>Rank of Suits\n    <p>The spade suit is always trump.</p>\n</h2>\n\n<h3>Rank of Cards\n    <p>A (high), K, Q, J, 10, 9, 8, 7, 6, 5, 4, 3, 2.</p>\n</h3>\n\n<h4>Object of the Game\n    <p>To win at least the number of tricks bid.</p>\n</h4>\n\n<h5>The Deal\n    <p>The first dealer is chosen by a draw for high card, and thereafter the turn to deal proceeds clockwise. The \n    entire deck is dealt one at a time, face down, beginning on the dealer\'s left. The players then pick up their cards \n    and arrange them by suits.</p>\n</h5>\n\n<h6>The Bidding\n    <p>Each player decides how many tricks he will be able to take. The player to the dealer\'s left starts the bidding \n    and, in turn, each player states how many tricks he expects to win. There is only one round of bidding, and the \n    minimum bid is One. Every player must make a bid; no player may pass. No suit is named in the bid, for as the name\n    of the game implies, spades are always trump.</p>\n</h6>\n\n<h7>The Play\n    <p>The game is scored by hands, and the winner must make a certain number of points, which is decided before the \n    game begins. Five hundred points is common, but 200 points is suitable for a short game. The player on the dealer\'s\n    left makes the opening lead, and players must follow suit, if possible. If a player cannot follow suit, he may play \n    a trump or discard. The trick is won by the player who plays the highest trump or if no trump was played, the player\n    who played the highest card in the suit led. The player who wins the trick leads next. Play continues until none of \n    the players have any cards left. Each hand is worth 13 tricks. Spades cannot be led unless played previously or \n    player to lead has nothing but Spades in his hand.\n</h7>\n\n<h8>How to Keep Score\n    <p>For making the contract (the number of tricks bid), the player scores 10 points for each trick bid, plus 1 point \n    for each overtrick. For example, if the player\'s bid is Seven and he makes seven tricks, the score would be 70. If \n    the bid was Five and the player won eight tricks, the score would be 53 points: 50 points for the bid, and 3 points \n    for the three overtricks. In some games, overtricks are called "bags" and a deduction of 100 points is made every \n    time a player accumulates 10 bags. Thus, the object is always to fulfill the bid exactly. If the player "breaks \n    contract," that is, if he takes fewer than the number of tricks bid, the score is 0. For example, if a player bids \n    Four and wins only three tricks, no points are awarded. One of the players is the scorer and writes the bids down, \n    so that during the play and for the scoring afterward, this information will be available to all the players. When \n    a hand is over, the scores should be recorded next to the bids, and a running score should be kept so that players \n    can readily see each other\'s total points. If there is a tie, then all players participate in one more round of \n    play.\n</h8>\n', editable=False, max_length=3000)),
            ],
        ),
    ]
